### ISSUE TITLE
English strings in localized versions of https://give.thunderbird.net/

### ISSUE THREAD

**Issue by Joergen** [mozilla/donate-wagtail#1019]
I noticed that the Danish version of the page "Give to Thunderbird" (https://give.thunderbird.net/da/) contains English strings. According to Pontoon all strings are localized.
Other locales have the same problem. (de and it).

**Comment by TheoChevalier** [comment]
Hi @Joergen, thanks for filing this!

Unlike other strings in the page, these are stored in a CMS (Wagtail) and it needs to support Pontoon. The initial plan was to have Pontoon support in Wagtail when we launched the new donate site in February, but it turned out additional work was needed. This work is being scoped, and we should have more clarity soon.

I’m closing this issue in favor of https://github.com/mozilla/donate-wagtail/issues/447 where you can track our progress.

Thanks for your patience! And of course feel free to reach out if you have questions
