### ISSUE TITLE
Campaign page

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#12]
**Overview:**

Similar page to the landing page, but can be tailored to a certain cause, allowing us to create custom campaigns targeting user groups or search terms. 

**Design / Wireframe:**

Desktop: https://redpen.io/te6a33f4a49c6b3522
Tablet: https://redpen.io/vx1e0d3503a45a7ac8
Mobile: https://redpen.io/tebe763a544821f642

**Components that form this template:**

- [x] Hero (image, title, introduction)
- [x] Partner logo (multiple)
- [x] Donation form
- [x] Legal footer text

**Comment by nicklee** [comment]
Started this, it's now blocked until design, PR can be found here:

https://github.com/mozilla/donate-wagtail/pull/50/

**Comment by beccaklam** [comment]
Hi @nicklee I was working on this design and had a question:
I was having trouble fitting the campaign header and text over the image and was talking to the other designers and they were saying that generally when they run into this problem they separate the image and text for mobile. But since I don't want the donate form to be hidden I was wondering if we could do a sticky button at the bottom of the mobile screen until the donate form shows up (upon which the button would disappear. If a user taps the button, it brings them to the donate form). I've updated the UX here in the redpen: https://redpen.io/pgc07b9e1e1cdf635b

**Comment by nicklee** [comment]
Hey, sounds like a good plan to me; We often end up adding scroll down functionality on full height heroes to ensure that users know there’s more content below the fold. From a front-end pov, it’s simple for us to implement too.

I’m away for a week now, but will look forward to seeing the progress when I’m back :)
