### ISSUE TITLE
Update footer to match styling of foundation.mozilla.org 

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1373]
The footer for the donate site has some minor differences in spacing and formatting from the foundation site 
(EX: Length and height of the newsletter sign up input, spacing and formatting of the links on the right side of the footer):

<img width="847" alt="image" src="https://user-images.githubusercontent.com/18314510/113188673-31a51800-920f-11eb-929c-7fe2c8a8c6ae.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/18314510/113188746-4aadc900-920f-11eb-848b-8ad21917dcf7.png">

 

We would like the donate site footer to match the styling of the foundation production site.

**Comment by TheoChevalier** [comment]
Hey, following up the discussion from #1358, since the sign up input field has shrunk on desktop, the placeholder is now truncated in multiple languages, including French, Japanese & Russian. We should make sure to test these as part of this PR

<img width="1200" alt="Capture d’écran 2021-04-06 à 10 07 37" src="https://user-images.githubusercontent.com/1294206/113679901-2e4ed800-96b8-11eb-9775-dc29c3261a04.png">

**Comment by Pomax** [comment]
Is this mostly a matter of updating the `col-...`  values to match?

**Comment by jamilasnell** [comment]
@kristinashu Is this something that should still be actioned on?

**Comment by kristinashu** [comment]
Which donate site is this for? The footer on donate.mozilla.org is much more simplified than the one on foundation.mozilla.org - I believe the intention of simpler footer is to focus users on donating. 

Screen cap from prod:
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1068783/146966376-e56fe2e7-0e37-4593-bc05-2d9179c35fed.png">

**Comment by Pomax** [comment]
Ah, perfect. If the focus for donate.moz was to have a simpler footer, then we can close this issue.
