### ISSUE TITLE
Sort Help page language dropdown alphabetically in all languages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#1561]
With a longer list of languages in the help form (#1560), we should dynamically sort the translation of those names alphabetically.

Right now it’s less usable to read through a long list that is not sorted alphabetically (it only is sorted in English)

We can leverage this line and move it to its own template tag to do proper string collation https://github.com/mozilla/donate-wagtail/blob/master/donate/core/templatetags/util_tags.py#L37

**Comment by Pomax** [comment]
As far as I'm aware the list of languages is not based on anything on the python side, it's purely HTML, so this would be a compound bit of work where we also make that list something that gets generated off of some context value from the Python side, instead of not knowing anything about Python or Django.

**Comment by Pomax** [comment]
closing as stale
