### ISSUE TITLE
Thunderbird FAQ strings missing from some languages in Pontoon

### ISSUE THREAD

**Issue by Sancus** [mozilla/donate-wagtail#1661]
Some languages appear to be missing the FAQ file/strings. For example, [`ru` does not](https://pontoon.mozilla.org/ru/donate-thunderbird-content/) have faq.pot. This leaves it impossible to localize these languages.

It seems like the strings are in [this repository](https://github.com/mozilla-l10n/thunderbird-donate-content) so it just needs to be updated following the process in the wagtail README?

**Comment by TheoChevalier** [comment]
Hi @Sancus,

I’m enabling translation of the TB FAQ page once locales are done migrating (or translating from scratch) the FAQ page in https://pontoon.mozilla.org/projects/donate-mozilla-content/, so that people are not overwhelmed with content.
I haven’t had a look recently, so I’ve just enabled a few locales (including Russian) that were complete for the Mozilla project

Thanks!
