### ISSUE TITLE
Email signup

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#17]
**Overview:**

Prompts the user to signup to the Mozilla email list by entering their email address, and confirming they have read the privacy policy. 

Step 4/5 (Landing/Campaign > Details > Payment > Upsell (optional) > Email signup) of the process, could potentially be optional, and could show for both monthly and one off donations. 

**Design / Wireframe:**

Desktop: https://redpen.io/eo137e0b58bf3ace18
Tablet: https://redpen.io/axd4e004cbcfbd16dd
Mobile: https://redpen.io/ahe3dd0e181414c277

**Components that form this template:**

- [x] Title
- [x] Sub title
- [x] Introductory text
- [x] Email signup form

**Comment by TheoChevalier** [comment]
Note that the email signup form needs to subscribe people to the most appropriate list in Salesforce.

So, we will want to allow users to pick a country and a language, like here https://www.mozilla.org/en-US/newsletter/mozilla/

- We support the same set of languages for the newsletter: English, German, French, Spanish, Polish, Portuguese.
- When someone is visiting the page with one of the locales above, the matching language is selected in the list by default. E.g. if my browser is set to pt-BR, Portuguese is the selected language in the list. Otherwise, English is the default.

@beccaklam Could you update the wireframes here to include:
- A country dropdown
- A language dropdown

**Comment by beccaklam** [comment]
@TheoChevalier Just a couple questions:
I'm wondering if we want to make the process as streamlined and easy for the user as possible could we just detect the language we've selected for them based on locale and detect the country from what they select for their payment details? Not against adding these drop downs, just asking to clarify.

**Comment by beccaklam** [comment]
@nicklee just a note that we're trying to streamline the email signup process. It's still in the works though since some key stakeholders are on vacation until next week. Design in process here: https://redpen.io/ykdc92900c06af901c This may mean we would remove the email sign up screen as step 4/5 (@alanmoo correct me if I'm interpreting our conversation with anil yesterday incorrectly).

**Comment by TheoChevalier** [comment]
@beccaklam I noticed the ongoing slack convo about that afterwards — and I totally agree we could streamline this as part of the details page (with selected locale + country field, as you mentioned), if we’re going down that route.

**Comment by solarissmoke** [comment]
> This may mean we would remove the email sign up screen as step 4/5.

There is a problem here: this details form is only show to someone making a card payment - we wouldn't have access to this information for someone who has paid with Paypal, because they go directly into Paypal's flow from the landing page.

I can think of two options here:

1. For Paypal, we have an email signup step after payment is collected. This would require implementing different workflows for Paypal vs card after payment is made.

2. We don't initialise the Paypal flow immediately on the landing page, but instead take users to to this detail form first. The information collected here is then passed to Paypal when initialising its flow (i.e., the user won't be asked to supply it again and the data will be prepopulated in Paypal's modal).

My preference is for option 2 because it lets us use this streamlined flow consistently for both payment routes.

**Comment by beccaklam** [comment]
I think #2 could work, what do you think @alanmoo ?

**Comment by alanmoo** [comment]
I think I want to ask Will on this one. I'll follow up with him early next week.

**Comment by solarissmoke** [comment]
Just to record the discussion we had verbally yesterday - the decision is to stick with the existing flow (i.e., newsletter signup happens after payment, for both card and paypal).

**Comment by nicklee** [comment]
This has been fully styled and is good for review:

https://github.com/mozilla/donate-wagtail/pull/124

**Comment by beccaklam** [comment]
Left some comments in ☝️
