### ISSUE TITLE
White space is not properly rendered for some currencies on Firefox on Mac

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#173]
Copied from  https://github.com/mozilla/donate-wagtail/pull/171#issuecomment-519028398:

> I’ve only noticed one tiny issue with the value in the button for this query https://donate-wagtail-staging-pr-171.herokuapp.com/fr/card/single/?source_page_id=3&currency=krw&amount=22320
>
> For some weird reason, only in Firefox (tried with a release build as well), and only for the button (no issue with the “You are donating 22 320 ₩” at the top), the space separator is not displayed. But you can see it’s there. And it works in Chrome.

Further testing isolated this specifically to Firefox on Mac OS.

**Comment by cadecairos** [comment]
This looks like it's related to `font-weight: 600` which is being inherited from `.button--large`

**Comment by jamilasnell** [comment]
Investigate to see if this issue still persists.

**Comment by danielfmiranda** [comment]
Hi Everyone, 
I do not believe this issue persists anymore as it seems there has been added logic to prevent the user from entering a value with a space in the middle for any currency. 

For example, here I am trying to donate 2000 Y with a space in between, however once I add a space in between 20 and 00 the button to change the value is then disabled like so: 
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/7eb5a94d-6b32-48af-a975-b74fc80934a6)

**Comment by TheoChevalier** [comment]
Hi @danielfmiranda, the bug occurs with the number formatting that follows the locale rules, not with the user inputted value (as you pointed, one can’t enter spaces in the field). It also only happens on the button below the form:

<img width="792" alt="Capture d’écran 2021-03-22 à 15 25 46" src="https://user-images.githubusercontent.com/1294206/112005431-a646cb00-8b1a-11eb-9f11-c08cf3da0a6a.png">

Now, looking closely, it seems there’s a space (between the first and second 0), but it’s really really thin, much thinner than in the box at the top:
<img width="472" alt="Capture d’écran 2021-03-22 à 15 27 31" src="https://user-images.githubusercontent.com/1294206/112005633-daba8700-8b1a-11eb-8cd6-95679fc3abea.png">


You should be able to reproduce on https://donate-wagtail.mofostaging.net/fr (you can’t reproduce with English, because this language doesn’t use spaces as digit separator) with `20000` as value.

**Comment by danielfmiranda** [comment]
Hi Theo, 

Thanks for the great write up! I followed the link you included and was able to reproduce the issue that the ticket is referencing.

Hi @kristinashu, 

After testing out the suggestion above, which was to reduce the font weight to 500, I can confirm that this resolves the issue. I was wondering if that would still be compliant with our design/accessibility standards?

**Comment by kristinashu** [comment]
Hi, sorry I am not too familiar with the donate page or this issue but is it correct to summarize the issue as: the form field currently does not allow for spaces but it should?

**Comment by danielfmiranda** [comment]
Hi @kristinashu!

No problem, to summarize the issue:

Whenever the user enters an amount such as 20000, it appears that the button at the bottom of the page is not displaying a small gap in between the 20 and 000 as a separator.

For example, here is what the number should look like, with a small gap acting as a separator in between 20 and 000:
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/1509b9c5-eb2f-4a8c-a7ef-8204f6c3ba37)


The button at the bottom of the page however does not seem to display/is hard to see that gap: 
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/703980f3-a49a-436f-92cd-7d4773a2738c)


Though we found that if we reduce the font weight from 600 to 500, the gap is more visible:
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/edf1a08d-07e1-4004-bd36-a9c60504d8bf)

So my question is, would it be OK for us to reduce the font weight of the purple button? Or will that not meet accessibility standards?

Thank you!

**Comment by kristinashu** [comment]
Thank you so much @danielfmiranda for explaining this to me! The lighter font weight looks good. Thank you for checking.

**Comment by danielfmiranda** [comment]
Hi Kristina, no problem! And thanks for confirming, just submitted a PR :)
