### ISSUE TITLE
Develop functional specification for campaign journey

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#3]
A functional specification for the campaign functionality will help us to ensure we've got all the required features covered (perhaps just this ticket can be the spec as we develop it). The bits that I think we've discussed already (but open to feedback/refinement):

- Ability to specify custom content on the landing page for a campaign.
- Ability to specify default donation amounts for a campaign (e.g, $3.14 for Pi day), in different currencies, with fallback to global defaults. (NB note from Jesse - "my strong preference so we don't wind up with a complex matrix of prices...").
- Ability to specify default donation frequency (single/monthly) for a campaign.
- Ability to specify the benefactor for a campaign and for this information to be passed through to Braintree.

Open questions/potential features to discuss:

- Custom content on thank you page after a donation is made?
- Confirmation email sent to donor (or is this handled separately via Salesforce)?

**Comment by alanmoo** [comment]
>* Custom content on thank you page after a donation is made?

Nice to have, but not necessary. 

There's some functionality that's a part of the post donation flow that is important to preserve though: One time->repeating donation upgrades, and hiding/showing the "sign up for our mailing list" depending on a query parameter. (So that when someone clicks on the "donate" button in an email, they don't get asked to sign up for the mailing list again at the end of the flow, as they're clearly already on it.)

>* Confirmation email sent to donor (or is this handled separately via Salesforce)?

Handled by Salesforce
