### ISSUE TITLE
UX upsell displayed different amount than what is logged in BrainTree

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#309]
Made a donation of $25, got the upsell ask for monthly of $3. Clicked yes. BrainTree reporting two transaction of $25. (Android/Chrome)

![2019_09_30_CC_25-donation-3-upsell](https://user-images.githubusercontent.com/11812272/65909879-c31b9b80-e386-11e9-9e79-2bf58ebd3367.JPG)

**Comment by solarissmoke** [comment]
@stephaniemcv the upsell creates a subscription, which is queried from a separate view in the Braintree dashboard (Subscriptions rather than Transactions). I'm pretty sure that what you're seeing here is just two transactions (i.e., initial donations) that were made in quick succession by testers. Grateful if you can check and confirm that under Subscriptions a subscription for the upsell amount is created.

**Comment by philwakefield** [comment]
Please confirm if this awnsers your question

**Comment by stephaniemcv** [comment]
I checked Subscriptions and I did see the $3 amount with 'Pending', so great! However, the two transactions are both me, made on an Android device, and I submitted once. I'll attempt to replicate and report back.

**Comment by solarissmoke** [comment]
There is a [setting in the Braintree control panel](https://articles.braintreepayments.com/control-panel/transactions/duplicate-checking) to prevent duplicate transactions, which I suspect hasn't been enabled. That should be turned on.

**Comment by alanmoo** [comment]
I did turn that on and I haven't noticed issues since.
