### ISSUE TITLE
Internal Server Error page

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#375]
Nice to have.

Mozilla brand applied to "Something went wrong" page.
![2019_10_03_ISE_500_unsucessful_verification](https://user-images.githubusercontent.com/11812272/66089809-f8b6b500-e53d-11e9-9ec0-689ec257155f.JPG)

**Comment by alanmoo** [comment]
@cadecairos is this a page that will actually show once live? Or would it be replaced by something else?

**Comment by cadecairos** [comment]
This is the default page that's showed when the application fails to respond due to a system level error or timeout. We can customize it with a static error page uploaded to S3, and setting that page's URL to `ERROR_PAGE_URL` and `MAINTENANCE_PAGE_URL` (we can have different pages for those settings as well if we want to customize the message)

For example, when the foundation site fails to respond for any reason, the Heroku router serves this page: https://s3.amazonaws.com/foundation-mozilla-org-maintenance/maintenance.html

**Comment by beccaklam** [comment]
I don't think we need any new design for this if Nick can just follow what's been done on the foundation site like what he did for the 404 page:  #78

**Comment by Pomax** [comment]
closing as out of date
