### ISSUE TITLE
Tech Spike - Pontoon integration

### ISSUE THREAD

**Issue by philwakefield** [mozilla/donate-wagtail#39]
To ensure we make the best implementation of pontoon we will undertake a tech spike to explore our approach

**Comment by ghickman** [comment]
While working on this I achieved:
* Pontoon running locally
* Demo wagtail project with wagtail-localize running locally
* Data repo on GitHub
* Create Translation Requests via wagtail-localize (pushed to data repo automatically)
* Translate files in Pontoon
* New files written back to the data repo by Pontoon

Here are my findings from getting that PoC working:

## Expected Pontoon Flow
* A Pontoon Project is configured to look at a given repo
* The Pontoon Project syncs that repo to a local directory
* The repo contents has the directory layout of `locales/<source_locale>/some/further/paths`
* A contributor provides translations via Pontoon
* Pontoon writes the changes to `locales/<destination_locale>/some/further/paths`, commits the changes, pushes to the repo remote


## Current wagtail-localize Flow.
When a user clicks "Create a translation request" localize creates a TranslationRequest for each requested locale.  When the user requests to download these, they pick a specific translation request they want and localize builds a .po file for them.


## Converting to Pontoons Flow
There are two main changes required for working with Pontoon: the ability to upload to GitHub, changing how .po files are generated.

### Uploading to GitHub
Uploading is relatively simple, there's an example script in `upload.py` which does the equivalent of `git pull && git push` (since you can only add content based on the latest commit).

There are a couple of edge cases to consider: hitting GitHub's per-token hourly rate limit and errors when pushing content to a non-HEAD sha.  I suspect both of these are very unlikely to happen in practice - the rate limit is 5K/hour and if it's just the wagtail site pushing to the data repo the chances of overlap are slim.

### Generating .po Files
Pontoon expects .po files to be for the source locales and creates .po files for the destination locales *configured in pontoon* to the given repo when they are created by a translator.  Currently wagtail-localize produces .po files for each destination locale.

Naming the .po files needs to be stabilised too.  Currently localize produces a file with the name `translation-N.po` where `N` is the ID for the given TranslationRequest.  However this means every request for translation creates an entirely new .po file and Pontoon would require translators to translate the entire file regardless of how much overlap there is.  Since a TranslationRequest for a Page (and its relevant ancestors) I'm sure a stable name can be found.
