### ISSUE TITLE
Transactions are not hitting SQS

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#397]
From @cadecairos in Slack:

>I can see the messages getting put into the django_rq queue, and getting processed, but it's not sending them to SQS

I don't believe the full flow was ever actually working, but I thought stuff was hitting SQS at some point. Since this is such a blocker for testing, can we try to coordinate on this tomorrow (Friday)?

**Comment by solarissmoke** [comment]
@alanmoo and I did some investigation, and verified that (a) messages are being sent to SQS and (b) something is reading those messages. Someone now needs to determine what's happening after that.

**Comment by cadecairos** [comment]
We determined that the value of `service` in the message to sqs is being read by basket and is being used to populate the field `payment_source` in SalesForce, and is being rejected because it only accepts 'stripe' or 'paypal'. Stephanie has added 'Braintree_Card' and 'Braintree_Paypal' to the valid values for that field and [I've opened a PR ](#419) to update the constants defined for this field.

**Comment by alanmoo** [comment]
Steph is getting transactions. If there are other problems, it’s worth a new issue.
