### ISSUE TITLE
Social sharing links on thank you page are non-functional

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#417]
The social sharing links on the thank you page are currently non-functional - presumably we want them to launch a sharer widget (for Facebook, Twitter), email message (for email), and copy a link to clipboard or something similar for links. 

For Facebook, Twitter and Email we can copy the [behaviour of the old site](https://github.com/mozilla/donate.mozilla.org/blob/9823bb7a671ede8a267e850faf00ff0f767db601/src/components/social.js). What is the desired behaviour of the "link" button?

**Comment by beccaklam** [comment]
@solarissmoke The copy link should copy the donate page's main page URL so that a user could easily share it on a platform of their choice. When a link is copied the link icon changes to the check mark. For an example, see the social buttons section of our style guide: https://foundation.mozilla.org/en/style-guide/

**Comment by solarissmoke** [comment]
@philwakefield this requires front-end work.

**Comment by nicklee** [comment]
@alanmoo do you have a facebook app id for mozilla? We need one for our social sharing component. 

Are you happy with the following sharing text (taken from the existing functionality)? `I donated to Mozilla today because I #lovetheweb. Join me and help fight for a better and healthier internet, for all.`

**Comment by alanmoo** [comment]
Oh, hm, good question- @beccaklam I think we've come across this before. IIRC, we were only able to share the link to Facebook using the generated URL, but not actually pre-fill share text. Is that right?

**Comment by nicklee** [comment]
I've added all of the code here: https://github.com/mozilla/donate-wagtail/pull/430 

We just either need a facebook api id, or need to rethink how we're best to do the facebook share

**Comment by beccaklam** [comment]
@nicklee @alanmoo So I talked to Kristina and it seems like what we do now for Facebook is just populate the OG tag since we can't pre-fill text, does that help?

**Comment by alanmoo** [comment]
That makes sense. @nicklee I believe the context here is that we don't have an official facebook presence, therefore no app id, which is apparently required to pre-fill text.

**Comment by alanmoo** [comment]
What else needs to be done here?

**Comment by TheoChevalier** [comment]
We need https://github.com/mozilla/donate-wagtail/issues/504, then updating links here https://github.com/mozilla/donate-wagtail/blob/master/donate/templates/pages/base_page.html#L8

The rest has been updated in  https://github.com/mozilla/donate-wagtail/commit/41e4d086a7074620032cb011e2d520b15e3564f9

**Comment by TheoChevalier** [comment]
Last bits: https://github.com/mozilla/donate-wagtail/commit/f0ccb4308ce123f301d23ba7f55131c1ddb48e3b and https://github.com/mozilla/donate-wagtail/commit/1a69f0d70b9fec126401857f8ac286dcb422f2c4
