### ISSUE TITLE
First Name not passing 

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#455]
For Paypal, credit card, one-time and recurring. None of the test transactions that create a new Contact Record have a passed a First Name.
View in Salesforce
![2019_10_14_SFDC_No_First_Name](https://user-images.githubusercontent.com/11812272/66773705-dcd7db00-ee7c-11e9-8b2b-5ec8b31e14bf.JPG)

View in BT (BT is not displaying on this list view the First/Last Name of Paypal customers, but IT IS on the individual record in BT.)
![2019_10_14_BT_First_Name](https://user-images.githubusercontent.com/11812272/66773713-e2cdbc00-ee7c-11e9-94fb-a40c40680a00.JPG)

(Windows 10, Firefox, Chrome)

**Comment by alanmoo** [comment]
@stephaniemcv I think I realized what's going on- presently, Stripe only has a single field for user name. I'm betting that translates to how Basket's designed to gather these. I tried passing Basket a `first_name` key but it's not doing anything; It also appears that these get consolidated in salesforce as a single field anyway. (In fact, I feel like we discussed this somewhere along the way).

@pmac can you confirm that this sounds like the right assessment of what's going on with Basket not passing a `first_name` into Salesforce from the donation endpoint?

If so, I think we have 2 options that don't require Basket modifications:

1.) Simply concat first/last name together when sending under the `last_name` key to Basket. Potential l10n issues (paging @TheoChevalier)

2.) Remove the "first name" field in the credit card form and relabel last name as simply "name"
I'm not sure what implications this might have. Does anyone tagged have thoughts?

**Comment by TheoChevalier** [comment]
That’s a complex internationalization topic, even if it sounds super trivial.

> 1.) Simply concat first/last name together when sending under the `last_name` key to Basket. Potential l10n issues (paging @TheoChevalier)

I think the concatenation itself is safe here, from a i18n perspective. I’m more concerned about the next step, with Salesforce doing the split itself when it needs a first name when sending the receipt.  But it has always been the case with the existing setup…

> 2.) Remove the "first name" field in the credit card form and relabel last name as simply "name"
> I'm not sure what implications this might have. Does anyone tagged have thoughts?

In this case, we should probably rename it as “Full name”, rather than  just “Name”. Here are some generic i18n guidelines when it comes to designing such field: https://www.w3.org/International/questions/qa-personal-names.en#fielddesign

That said, neither solution is perfect, and there are arguments on both sides:

- Since we’re letting Salesforce do the split, with the first one, we can control the order, such that we’re making sure to pass `Théo Chevalier` to Salesforce, while we could end up with `Chevalier Théo` with the second one. In such case, Salesforce would wrongly pick Chevalier as the first name. As explained here, some cultures are usually writing `Last name` then `first name`: https://www.w3.org/International/questions/qa-personal-names.en#partorder

- Some people don’t have last names, so requiring a last name can also cause issues. “Similarly, don't require that people supply a family name. In cultures such as parts of Southern India, Malaysia and Indonesia, a large number of people have names that consist of a given name only, with no patronym. If you require family names, you may create significant problems in these cultures, as users enter garbage data like "." or "Mr." in the family name field just to escape the form.”

So… maybe we can keep two separated fields, concatenate them, BUT make the last name field not required?

Tagging with l10n-impact, as in either case, we will likely need a new string

**Comment by pmac** [comment]
There are several things at play. Our usual deal is to avoid changing a name if the user already has one set. Salesforce does not require a first name, but does require a last name, so if we get no name then we have a default value for last name that we use. 

Basket is the thing that does the splitting if it doesn't get both a first and last name. So if you'd like to discuss the best way to handle that we can make it work I'm sure.

Unfortunately salesforce is married to its short-sighted "first name" and "last name" approach, so there isn't much we can do there. But we can put whatever we want in those fields and use them as we wish as long as something goes in last name.

**Comment by alanmoo** [comment]
So, I realized my PR actually works by simply adding a first name to be passed to Basket and I was testing things incorrectly or something. This issue's been closed, but @TheoChevalier I'll leave it to you to open a new issue for optimizing this for l10n purposes, given the constraints above. It seems like we're all on the same page and what we might want is:

* Two fields in the web form that get passed to Basket.
* Basket keeps them as they are and passes to Salesforce, but if there's no last name, it fills in the default one.

The one question here then is what to do about form validation. We presumably really want last names from countries where that's standard, so I'd imagine fundraising would not be keen on making the last name field optional...
