### ISSUE TITLE
Accordion content is not extracted in .po files

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#518]
I’ve added an accordion component with a few question/answers for testing purposes on https://donate-wagtail.mofostaging.net/en-US/faq/ then synced content with the Pontoon repo, and only the page title + CTA got synced: https://github.com/kaedroho/mozilla-donate-staging-content/commit/0d1db03f372f6859cd45170a05338dd4f2e8115b

**Comment by kaedroho** [comment]
Hi @TheoChevalier 

The accordion items are in list blocks, but these aren't supported by Wagtail localize at the moment as there isn't a way to uniquely identify the items in the list.

There are a couple of options for workarounds for this:

**1) Use a StreamBlock instead of a list block**

This would change the UI and representation of the blocks in the database, but each block in a StreamBlock is assigned a UUID so there isn't a problem with identifying them)

**2) Manually implement segment extraction/ingestion for this block type**

This can be done by implementing a couple of methods on your `AccordionBlock` class, for example:

```python

from wagtail_localize.segments import SegmentValue

class AccordionBlock(blocks.StructBlock):
    ...

    def get_translatable_segments(self, block_value):
        # Converts the block_value into a list of SegmentValue objects
        segments = [
            SegmentValue("title", block_value["title"]),
        ]

        # TODO add segments from items

        return segments

    def restore_translated_segments(self, block_value, segments):
        # Replaces the block_value with the content from the passed in translated segments
        for segment in segments:
            if segment.path == "title":
                block_value["title"] = segment.text

                # TODO items
```

**Comment by TheoChevalier** [comment]
Thanks Karl! 
@alanmoo , not sure what we should do here?

**Comment by solarissmoke** [comment]
@alanmoo I think the simplest fix here is to switch to using a streamblock (option 1 suggest by Karl above). This will make the edit UI a little more complex, but given that this content doesn't change frequently I don't think that should be a big issue. Let me know if you want us to make this change?

**Comment by alanmoo** [comment]
I agree, it shouldn't be a big issue. If there's still bandwidth to do it, yes, that would be great.
