### ISSUE TITLE
Confirm copy

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#522]
Confirm final copy across the site

**Comment by TheoChevalier** [comment]
@WillatMozFdn For awareness, the only changes I’ve made to the FAQ/Ways to give copy are:

- In question #2 (How does Mozilla ensure my personal information is protected?), I’ve replaced Stripe with Braintree (and updated the link to Braintree’s privacy policy)

- Swapped the address for sending checks to the SF office

Copy that needs to be updated:

- [ ] Bitcoin question
- [ ] Sending a check: `Please send a check including your email address on the memo line, and payable (payee) to “Mozilla Foundation”` ← We’re losing our customization here, this copy will be used for all languages, instead of `Please send a cheque with a separate note including your email address, and payable (payee) to “Mozilla Foundation”`. Do we want to add “If you don’t have a memo line… etc”?

https://give.mozilla.org/en-US/faq/
https://give.mozilla.org/en-US/ways-to-give/

**Comment by WillatMozFdn** [comment]
for https://donate.mozilla.org/en-US/faq#item_5 ...

old text, delete:
At this time, we are unfortunately unable to accept bitcoin donations. We are currently investigating new solutions around reenabling bitcoin donations.

new text, add:
**Yes!** As of November 2019, the Mozilla Foundation can now accept donations of Bitcoin and Bitcoin Cash. You can read our [FAQ page here](https://wiki.mozilla.org/Donate_Bitcoin) and/or make a donation via our [hosted page on Bitpay here](https://bitpay.com/100257/donate).
