### ISSUE TITLE
Migration: End stripe subscription/create Braintree one on webhook event

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#574]
We need to move recurring donors from Stripe to Braintree.

More details to come

**Comment by gideonthomas** [comment]
Assigning @cadecairos for now to investigate how much of this is possible and add info about how to do this.

I will follow up with our account manager to find out how to migrate payment info from stripe to Braintree.

**Comment by gideonthomas** [comment]
cc @alanmoo

**Comment by gideonthomas** [comment]
We have a set order of operations to adhere to:
1. Stripe exports customer data (including payment info) (which is within the next few days)
2. Braintree imports customer data and gives us a log file with customer ids.
3. The webhook changes to recreate subscriptions in Braintree (and cancel corresponding stripe subscriptions) goes live.
4. Stripe exports customer data again to catch new subscribers between the date of the first export and launch of the new donation platform on donate.mozilla.org.
5. Braintree imports this second set of customer data.
6. The webhook continues to run.

Important Caveats:
- The new donate.mozilla.org platform launch is blocked on our MZLA Braintree account being set up AND recurring donors for MZLA being dealt with.
- We should aim to have the webhook changes (step 3) live close to when the first email is sent out to the public about the new platform on its temporary url.
- We should aim to have step 4 and 5 done within 1 month from when we do step 1. i.e. second export/import should happen within 1 month after the first export/import. Unfortunately, step 4 and 5 depend on donate.mozilla.org hosting the new platform which in turn depends on the MZLA account being setup and used on the MZLA donation site.
   - If we aren't able to have step 4 and 5 done by that time, we will need to add an exception in the webhook to ignore customers not found in Braintree (i.e. new subscribers after step 1) so that it can migrate the subscription during the next webhook event (which hopefully should be after step 4 and 5). TODO: figure out messaging in the receipt around this.

cc @cadecairos

**Comment by alanmoo** [comment]
The aim is to land this Jan 27.

**Comment by stephaniemcv** [comment]
So does updating dates to 11/22 to 1/26 sound right?

**Comment by alanmoo** [comment]
I believe you'd be looking for 11/22 to 1/28 based on the description in @gideonthomas's post.

**Comment by gideonthomas** [comment]
Updated the description in my comment with dates.

@stephaniemcv to clarify (since there are so many dates), the MoFo recurring donor export from Stripe needs to happen on the day **after** launch. The MZLA recurring donor export from Stripe/PayPal (for cancellation) needs to happen **on the day of launch**.

**Comment by stephaniemcv** [comment]
Thanks for the clarification!

**Comment by gideonthomas** [comment]
@stephaniemcv is this something you're able to do by early next week?
