### ISSUE TITLE
Source changes aren’t propagated to localized pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#755]
This is likely a dupe of https://github.com/mozilla/donate-wagtail/issues/554 and being taken care of in https://github.com/wagtail/wagtail-localize/pull/47 @kaedroho, do you confirm?

Changes made to a page that has existing localizations are not propagated to the localized pages.

Example: Removing, adding or changing strings (or updating a link) in English on https://donate-wagtail.mofostaging.net/en-US/ways-to-give doesn’t trigger an update of https://donate-wagtail.mofostaging.net/fr/ways-to-give

The localized pages should be updated upon hitting "Save", or at least when syncing.

Currently, they are only updated when changes are made on Pontoon for this locale + file.

**Comment by kaedroho** [comment]
The recent update changed some logic so that non-translated content is always synced at the same time as translated content (instead of pushing those changes straight through on save which could lead to inconsistency).

This might've caused an issue when there are only changes to non-translatable content as the Pontoon sync code is only run when translated strings are sent back to Wagtail.

I'll look into making it detect when there are no changes to be submitted to Pontoon and perform the sync immediately on save.

**Comment by TheoChevalier** [comment]
Fixed by https://github.com/mozilla/donate-wagtail/pull/1218
