### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#757]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1682681/72640774-95a72d80-3936-11ea-931a-2c1f7dd43a5e.png">

Notice lines 8, 13, and 20 - Let's remove the duplication and change it to "Give to Thunderbird" (line 21 should be updated too). We should keep "Donate to Mozilla" on the MoFo version of the site.

**Comment by mmmavis** [comment]
Current page title:
> Donate to Thunderbird | Give to Thunderbird

The string after the `|` is coming from CMS. I can clear those fields on CMS but this won't prevent other editors from editing those fields in the future. 

Below I've included logic (and added whitespace to make the following code more legible) for `<title>`. I think we should update it so that the chunk before pipe comes from CMS and after the pipe we show `Give to Thunderbird`. Thoughts?

e.g., 

By default we use `Give to Thunderbird` as the title on all pages. If there's meta set in CMS, we prepend the string so the title would read `Title from CMS | Give to Thunderbird`. Thoughts?

```python
{% block title_prefix %}

{% if request.site and page.pk == request.site.root_page.pk and request.site.site_name %}
{% trans 'Donate to Thunderbird' context 'Page title' %} | 
{% endif %}

{% endblock %}


{% block title %}

{% if page.seo_title %}
{{ page.seo_title }}
{% else %}
{{ page.title }}
{% endif %}

{% endblock %}


{% block title_suffix %}

{% if request.site and page.pk != request.site.root_page.pk and request.site.site_name %}
 | {% trans 'Donate to Thunderbird' context 'Page title' %}
{% endif %}

{% endblock %}
```

**Comment by alanmoo** [comment]
I think that makes a whole lot of sense! You're probably on it, let's take the same approach for the Foundation stack too.
