### ISSUE TITLE
Clicking the Paypal Button triggers error if no amount is selected

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#761]
STR:

1. Load the donation form
2. Click the Paypal button

Expected: An error about selecting an amount
Actual: A generic "There was an error processing your payment. Please try again." message appears.

**Comment by tagniam** [comment]
Hi @cadecairos, since this issue was opened, there's been a code change that prevents an error message from occurring at all. 

It looks like an overlay (`payments__button--paypal--overlay`) on the PayPal button is inserted if there is no amount/an invalid amount in the Other Amount input (`amount-other-input`) to prevent the user from clicking the PayPal button: https://github.com/CSCD01/donate-wagtail-team34/blob/master/source/js/payments-paypal.js#L106

To fix this (i.e. actually display an error message) it looks like an error needs to be thrown in the on click listener when the input is invalid.
