### ISSUE TITLE
Ability to preselect donation amounts in a link to donation landing page

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#844]
In our prior setup, we used to have the ability to pre-select one of the donate buttons on the page by using an "amount=XX" querystring, like this ... https://donate.mozilla.org?presets=3,9,27,75&amount=3 .  (Very useful for something like Pi Day fundraisers, where we ask for $3.14, $15.92, etc.)

However, this capability was lost in the transition to Wagtail and Braintree.  We need to restore it to get back to the basic functionalities we had in the old system.

**Comment by Pomax** [comment]
Does this need to change the amounts for the one-time, or also the monthly?

**Comment by Pomax** [comment]
@WillatMozFdn @cadecairos the code currently force-sorts the presets list, which seems pretty silly - if I take that out, I'll have to rewrite tests that ensure presets are sorted, so I can either:

1. remove sort-by-default but add it as optional query arg, or
2. keep sort-by-default but add an optional query arg to _bypass_ it.

Personally, I'd go with 1, because it's not exactly rocketscience to make sure the preset values are in the order you want shown =)

**Comment by WillatMozFdn** [comment]
Hey @Pomax , 

A. MVP, especially for Pi Day, is just for the one-timers.  Ideally/if not too hard, we could also do it for monthlies as well -- that would be really helpful for Jesse Ward trying to get major donors to give monthly.

B. I like #1 as well, let's go that way -- your reasoning is sound. :-)

**Comment by Pomax** [comment]
it's a def. more work to add in monthlies too, so doing A for now and monthlies later sounds good.  (let's file a separate issue for that work)
