### ISSUE TITLE
Pontoon sync error: ContentPage.DoesNotExist: ContentPage matching query does not exist.

### ISSUE THREAD

**Issue by patjouk** [mozilla/donate-wagtail#852]
https://sentry.prod.mozaws.net/operations/donate-mozilla-org/issues/7352631/

```
ContentPage.DoesNotExist: ContentPage matching query does not exist.
(11 additional frame(s) were not displayed)
...
  File "wagtail_localize/translation/models.py", line 192, in create_or_update_translation
    original = self.as_instance()
  File "wagtail_localize/translation/models.py", line 154, in as_instance
    instance = self.object.get_instance(self.locale)
  File "wagtail_localize/translation/models.py", line 60, in get_instance
    translation_key=self.translation_key, locale=locale
  File "django/contrib/contenttypes/models.py", line 168, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
  File "django/db/models/query.py", line 408, in get
    self.model._meta.object_name
```

and

```
 12:30:19.658 donate-wagtail-production logplex <190>1 2020-02-25T11:30:19.459741+00:00 host app worker.1 - 11:30:19: Pull: Importing changes in file 'locales/de/pages/mozilla-donate/ways-to-give.po'
12:30:20.484 donate-wagtail-production logplex <190>1 2020-02-25T11:30:20.167469+00:00 host app worker.1 - 11:30:20: Saving translation for 'pages/mozilla-donate/ways-to-give' in German
 12:30:20.490 donate-wagtail-production logplex <190>1 2020-02-25T11:30:20.207631+00:00 host app worker.1 - 11:30:20: donate.core.models.ContentPage.DoesNotExist: ContentPage matching query does not exist. 
```

**Comment by TheoChevalier** [comment]
Hey @kaedroho, our prod instance is stuck because of this, could you check my theory below?

Since the last sync:
- We removed /ways-to-give from the CMS, because we moved this page to [its own template](https://github.com/mozilla/donate-wagtail/blob/master/donate/templates/pages/core/ways_to_give_page_master.html) 
- There’s been [new translations](https://github.com/mozilla-l10n/mozilla-donate-content/commit/c9afd0a509858456ee818384fc6577f24c48ee33) for this very page 

My theory is that Wagtail first attempted to update translations for this deleted page, instead of starting with deleting the .po files. Should we file an issue somewhere?

For debug purposes, this sync processed all 5 commits from yesterday: https://github.com/mozilla-l10n/mozilla-donate-content/commits/master

**Comment by cadecairos** [comment]
@kaedroho Should we file this issue in `wagtail-localize-pontoon`? If we do can we expect a fix or will we need to open a PR ourselves?

**Comment by kaedroho** [comment]
Hi everyone, sorry I missed this issue before.

> My theory is that Wagtail first attempted to update translations for this deleted page, instead of starting with deleting the .po files. Should we file an issue somewhere?

Yep, It looks like Wagtail localize is trying to make a translation of a deleted page, I'll look into this when I next have time (I'll try to make some time for this over the next few days).

I'm happy to use this issue to track this bug as I'm not sure which plugin this bug is in yet. So I could find it later, please could the "Localisation" label be added to this issue?

**Comment by TheoChevalier** [comment]
Fixed by https://github.com/mozilla/donate-wagtail/pull/1218
