### ISSUE TITLE
Thank you for submitting a case page blank after save

### ISSUE THREAD

**Issue by phildexter** [mozilla/donate-wagtail#977]
As per #866, pages are appearing blank in multiple languages. English is fixed in previous ticket, this is to tackle other langauges.

**Comment by cadecairos** [comment]
After investigation, we've discovered the following information:

- in [donate/core/models.py](https://github.com/mozilla/donate-wagtail/blob/dd48cf87f948f5766692e8117140397326b50e8a/donate/core/models.py#L228-L237) we change the slug of localized pages to include a suffix corresponding to the page locale.
- in [wagtail/code/models.py](https://github.com/wagtail/wagtail/blob/baa4accbd0c2c5bbeab38b9d30341f18e5b3a19a/wagtail/core/models.py#L748-L773) Wagtail attempts to find the root page of the current page, but fails because the root page of the site has a slug of `/donate-wagtail/` and localized pages will always have the slug be `/donate-wagtail-{locale}/`. This will never resolve and it always returns `None`
- [In our code that overrides the default slug of saved pages](https://github.com/mozilla/donate-wagtail/blob/dd48cf87f948f5766692e8117140397326b50e8a/donate/core/models.py#L229) we made a note that "This slug isn't used anywhere". this is false, as shown in the point above.

It seems the only way to fix this is to look at wagtail-localize-pontoon and re-architect how it's using slugs to find pages during the two-way sync.

@phildexter This is probably not a 5.  

@kaedroho Any idea if this is a straight-forward fix for wagtail-localize-pontoon, or will it require some serious investment of time?

**Comment by Pomax** [comment]
closing as out of date
