### ISSUE TITLE
Error message styling

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#98]
We will need to apply styling to error messages that are rendered in various places:

1. Paypal error if you close the Paypal modal after loading it on the landing/campaign page.
2. Form errors on the card details view (to trigger this, disable browser validation and enter say an invalid email address), and for all other forms (upsell, newsletter).
3. Gateway errors on the card details view (to trigger this, enter a postcode longer than 9 characters for a US address).

**Comment by alanmoo** [comment]
@beccaklam It feels like this is related to https://github.com/MozillaFoundation/Design/issues/344, which it seems we punted on but is pretty important to figure out at this point.

**Comment by beccaklam** [comment]
Hi @philwakefield and @alanmoo I updated the details/payment form with an error state yesterday. Do you need any more styling direction than that? https://goo.gl/maps/GFsgz1vu1jjZm3Gx9
<img width="354" alt="Screen Shot 2019-07-25 at 9 54 49 AM" src="https://user-images.githubusercontent.com/20977376/61880154-5b4a5f80-aec2-11e9-8c3b-35e397f8a87d.png">

**Comment by beccaklam** [comment]
@nicklee more elaboration on error messaging. Can we change the required field error message to match below?
![Mobile  Error Messages@2x](https://user-images.githubusercontent.com/20977376/61905326-d2015000-aef6-11e9-9fde-20c9e8ebcd1c.jpg)

**Comment by nicklee** [comment]
Hi @beccaklam, thanks for this, the required star is shown on the normal form, before validation has occured, we don't seem to have an indication as to which fields are required in the designs, is this intentional?

We only get a single "this field is required" validation message with the current setup, I've styled this to get it as close to your designs as possible (error message at the top is larger size due to this being on mobile):

![Screenshot 2019-07-30 at 10 59 28](https://user-images.githubusercontent.com/298766/62120333-48b49980-b2b9-11e9-9c81-36d0373736db.png)

**Comment by beccaklam** [comment]
Sorry @nicklee, I know you've asked this question a couple times. Below should be the styling for any required field but in my opinion we should only be asking for required fields to cut down on form fatigue. Therefore it seemed a bit redundant to denote which were required fields since they all should be ... but @alanmoo do you know which ones are required and which ones are superfluous but we use for communication purposes? 
![Screen Shot 2019-07-30 at 9 21 37 AM](https://user-images.githubusercontent.com/20977376/62132667-77c40e80-b2ab-11e9-8b92-4d8b67637ec3.png)

**Comment by alanmoo** [comment]
I'm like 99% sure all fields are required. @solarissmoke would be able to definitively answer if the API doesn't require one of them...I suppose first name isn't technically required from a basket standpoint, but Braintree probably needs it.

**Comment by solarissmoke** [comment]
Actually _none_ of these fields are required by Braintree - it's possible to create an anonymous customer. But:

1. We'd probably want at least an email address to be able to identify the customer in Braintree.
2. Address information is needed if you want to be able to do [address verification](https://articles.braintreepayments.com/guides/fraud-tools/basic/avs-cvv-rules) on cards. This might be something to discuss with Braintree - the documentation doesn't seem to recommend this, but it might mitigate carding attacks.

**Comment by alanmoo** [comment]
We definitely want email to send receipts.

@WillatMozFdn Do we collect address to mitigate fraud?

**Comment by WillatMozFdn** [comment]
@alanmoo -- yes, mailing address is an important piece of our anti-fraud efforts, and my pretty strong feeling is that we WILL want to enable AVS.  Our fraudsters are pretty relentless.

**Comment by cadecairos** [comment]
This was resolved
